---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hazel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  
spec:
    destination:
        server: https://kubernetes.default.svc

    syncPolicy:
        automated:
        prune: true
        selfHeal: true
    replicaCount: 3

    image:
      repository: gcr.io/heptio-images/ks-guestbook-demo
      tag: 0.1
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80
