apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazel
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hazel
  template:
    metadata:
      labels:
        app: hazel
    spec:
      containers:
      - image: hazelcast/hazelcast:latest
        name: hazel

---
apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
spec:
  type: ClusterIP
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: hazel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5701
