---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: management-center
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: management-center
   spec:
     containers:
     - name: hazelcast
       image: hazelcast/management-center

---
apiVersion: v1
kind: Service
metadata:
  name: management-center-svc
spec:
  type: NodePort
  selector:
    app: management-center
  ports:
    - protocol: TCP
      port: 8666
      targetPort: 8666
  
  
