---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-hazelcast-management-center
spec:
  selector:
    matchLabels:
      app: pod-hazelcast-management-center
  template:
    metadata:
      labels:
        app: pod-hazelcast-management-center
    spec:
      containers:
        - image: hazelcast/management-center:latest
          # Always from local, never from Dockerhub
          #imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: service-hazelcast-management-center
spec:
  ports:
    - protocol: TCP
      port: 8666
      targetPort: 8666
  selector:
    app: pod-hazelcast-management-center
  type: NodePort
