---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-center
spec:
  selector:
    matchLabels:
      app: management-center
  template:
    metadata:
      labels:
        app: management-center
    spec:
      containers:
        - image: hazelcast/management-center:latest
          # Always from local, never from Dockerhub
          #imagePullPolicy: Never
                    # Url to check every 10 seconds if the container is ok
          livenessProbe:
            httpGet:
              path: /health
              port: 8666
            initialDelaySeconds: 180
          name: container-hazelcast-management-center
          # Url to check the container is up
          readinessProbe:
            httpGet:
              path: /health
              port: 8666
            initialDelaySeconds: 180

---
apiVersion: v1
kind: Service
metadata:
  name: management-center
spec:
  type: NodePort
  selector:
    app: management-center
  ports:
    - protocol: TCP
      port: 8666
      targetPort: 8666
  
  
